name: qwshortlink

services:
  frontend:
    image: qwshortlink-frontend
    container_name: qwshortlink-frontend
    pull_policy: never
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app:z
      - /app/node_modules
    depends_on:
      - backend

  backend:
    image: qwshortlink-backend
    container_name: qwshortlink-backend
    pull_policy: never
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app:z
    depends_on:
      - db
      - redis

  db:
    image: postgres:18.3-trixie
    container_name: qwshortlink-db
    restart: always
    shm_size: 128mb
    env_file:
      - ./db/.env
    volumes:
      - db_data:/var/lib/postgresql

  redis:
    image: redis:8.6.2-trixie
    container_name: qwshortlink-redis
    restart: always
    volumes:
      - ./redis:/usr/local/etc/redis:z
    command: redis-server /usr/local/etc/redis/redis.conf

volumes:
  db_data:
