name: qwshortlink

services:
  frontend:
    image: qwshortlink-frontend
    container_name: qwshortlink-frontend
    pull_policy: never
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    env_file:
      - ./frontend/.env
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app:z
      - /app/node_modules
    depends_on:
      backend:
        condition: service_started

  backend:
    image: qwshortlink-backend
    container_name: qwshortlink-backend
    pull_policy: never
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    env_file:
      - ./backend/.env
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app:z
    command: sh -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      celery:
        condition: service_started

  celery:
    image: qwshortlink-backend
    container_name: qwshortlink-celery
    pull_policy: never
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app:z
    command: celery -A config worker -l INFO

  celery_beat:
    image: qwshortlink-backend
    container_name: qwshortlink-celery-beat
    pull_policy: never
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app:z
    command: celery -A config beat -l INFO
    depends_on:
      db:
        condition: service_healthy
      celery:
        condition: service_started
      backend:
        condition: service_started

  db:
    image: postgres:18.3-trixie
    container_name: qwshortlink-db
    restart: always
    shm_size: 128mb
    env_file:
      - ./db/.env
    volumes:
      - db_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:8.6.2-trixie
    container_name: qwshortlink-redis
    restart: always
    env_file:
      - ./redis/.env
    volumes:
      - ./redis:/usr/local/etc/redis:z
    command: redis-server /usr/local/etc/redis/redis.conf
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a $${REDIS_PASSWORD} ping | grep PONG"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  db_data:
