# Generated by Django 6.0.3 on 2026-04-18 13:46

import django.db.models.deletion
import links.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
                ('short_code', models.CharField(default=links.models.generate_short_code, editable=False, unique=True, verbose_name='short code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'link',
                'verbose_name_plural': 'links',
                'indexes': [models.Index(fields=['url'], name='links_link_url_d67630_idx'), models.Index(fields=['short_code'], name='links_link_short_c_886f39_idx')],
            },
        ),
    ]
