# Generated by Django 6.0.3 on 2026-05-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="auth_method",
            field=models.CharField(
                choices=[("email", "Email"), ("google", "Google")],
                default="email",
                editable=False,
                max_length=32,
                verbose_name="authentication method",
            ),
        ),
    ]
